name: Build libnametag
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nttld/setup-ndk@v1
        id: ndk
        with:
          ndk-version: r25c
      - name: ndk-build
        run: |
          ${{ steps.ndk.outputs.ndk-path }}/ndk-build \
            NDK_PROJECT_PATH=. \
            APP_BUILD_SCRIPT=./jni/Android.mk \
            NDK_APPLICATION_MK=./jni/Application.mk \
            -j$(nproc)
      - name: Verifikasi
        run: |
          ls -lh libs/armeabi-v7a/
          file libs/armeabi-v7a/libnametag.so
      - uses: actions/upload-artifact@v4
        with:
          name: libnametag-arm32
          path: libs/armeabi-v7a/libnametag.so
